on:
  push:
    branches:
    - main
    - release/*
  workflow_dispatch:

jobs:
  helm_package:
    name: Package Helm Chart
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        name: Checkout

      - run: |
         echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | helm registry login registry-1.docker.io -u ${{ vars.DOCKER_HUB_USERNAME }} --password-stdin  
         helm package govna/
         helm push govna-0.1.0.tgz oci://registry-1.docker.io/${{ vars.DOCKER_HUB_USERNAME }}/govna
        name: Package and Push Helm Chart