on:
  push:
    branches:
    - main
    - release/*
  workflow_dispatch:

jobs:
  helm_package:
    name: Package Helm Chart
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Package Helm Chart
        uses: helm/chart-releaser-action@v1.2.0
        with:
          chart_path: ./govna
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_name: govna
          chart_version: 0.1.0
          chart_repo: