on:
  push:
    branches:
    - main
    - release/*
  workflow_dispatch:

jobs:
  helm_package:
    name: Package Helm Chart
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
         echo "${{ secrets.DOCKER_HUB_PASSWORD }}" helm registry login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin  registry-1.docker.io  